import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";

const poppins = Poppins({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Glasses",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
